version: '2'
services:
  traefik:
    image: traefik:latest
    hostname: traefik
    volumes:
    - /nfs/knas1/containers/traefik/config/:/etc/traefik/
    dns:
    - 216.52.126.1
    ports:
    - 8089:8080/tcp
    - 80:80/tcp
    - 443:443/tcp
    labels:
      traefik.enable: 'true'
      io.rancher.cni.network: ipsec
      traefik.http.routers.api.tls: 'true'
      io.rancher.cni.wait: 'true'
      traefik.http.routers.api.rule: Host(`traefik.knoll.duckdns.org`)
      traefik.http.routers.api.middlewares: https@file,retries@file,whitelist@file
      io.rancher.scheduler.affinity:host_label: node.type=compute
      traefik.http.routers.api.service: api@internal
      traefik.http.routers.api.tls.certresolver: letsencrypt
      io.rancher.container.pull_image: always
